# Generated by Django 2.1.4 on 2019-02-14 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number_text', models.CharField(max_length=1)),
            ],
        ),
        migrations.DeleteModel(
            name='Numbercal',
        ),
    ]
