# Generated by Django 2.1.4 on 2019-02-14 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20190214_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='number',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
